auth:
  access_token_ttl: 150m
  refresh_token_ttl: 300m
  jwt_secret: "secret"

db:
  allow_selection: true

server:
  host: localhost
  port: 8081
  max_header_bytes:  1048576
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s

logger:
  level: info
  development: false
  disable_caller: true
  disable_stacktrace: true
  encoding: json
  output_paths: 
    - ./logs/app.log
    - stdout
  error_output_paths:
    - ./logs/error.log
    - stderr
  environment: production
  service_name: desktop-lab
  enable_sampling: true
  sampling_initial: 100
  sampling_thereafter: 100
  max_file_size_mb: 100
  max_backups: 5
  max_age_days: 30
  compress_logs: true