// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {embed} from '../models';
import {context} from '../models';

export function AddContextDimensionToMaterial(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function AddDimension(arg1:models.ContextDimension):Promise<void>;

export function CreateGroup(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.ExperimentGroup>;

export function CreateMaterial(arg1:string,arg2:string):Promise<models.Material>;

export function CreateProtocolWithSample(arg1:models.CreateProtocolRequest):Promise<models.Protocol>;

export function CreateStandard(arg1:models.CreateStandardRequest):Promise<string>;

export function DeleteContextDimensionFromMaterial(arg1:string,arg2:string):Promise<void>;

export function DeleteDimension(arg1:string):Promise<void>;

export function DeletePossibleValues(arg1:string):Promise<void>;

export function EmitEvent(arg1:string,arg2:any):Promise<void>;

export function GenerateGroupSummaryPDF(arg1:string):Promise<string>;

export function GenerateProtocolPDF(arg1:string):Promise<string>;

export function GetAvailableDimensions():Promise<Array<models.ContextDimension>>;

export function GetContextDimensionsByMaterialID(arg1:string):Promise<Array<models.ContextDimension>>;

export function GetGroupByID(arg1:string):Promise<models.ExperimentGroup>;

export function GetGroupSummary(arg1:string):Promise<models.GroupSummary>;

export function GetGroups(arg1:number,arg2:number):Promise<models.GroupListResponse>;

export function GetMaterialByID(arg1:string):Promise<models.Material>;

export function GetMaterials():Promise<Array<models.Material>>;

export function GetMethodDetails(arg1:string):Promise<models.TestMethodFull>;

export function GetMethodsByStandardID(arg1:string):Promise<Array<models.TestMethod>>;

export function GetMethodsFullByStandardID(arg1:string):Promise<Record<string, models.TestMethodFull>>;

export function GetProtocolFull(arg1:string):Promise<models.ProtocolFull>;

export function GetProtocols(arg1:number,arg2:number):Promise<models.ProtocolListResponse>;

export function GetProtocolsByGroupID(arg1:string):Promise<Array<models.Protocol>>;

export function GetStandardDimensions(arg1:string):Promise<Array<models.ContextDimension>>;

export function GetStandardsByMaterialID(arg1:string):Promise<Array<models.Standard>>;

export function Init(arg1:embed.FS,arg2:embed.FS):Promise<void>;

export function InvalidateStandardCache(arg1:string):Promise<void>;

export function LinkDimensionToStandard(arg1:context.Context,arg2:string,arg3:string):Promise<void>;

export function LogFrontendEvent(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function SaveGroupPDFWithDialog(arg1:string):Promise<string>;

export function SaveProtocolPDFWithDialog(arg1:string):Promise<string>;

export function UpdatePossibleValues(arg1:string,arg2:Array<string>):Promise<void>;
