// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateGroup(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.ExperimentGroup>;

export function CreateMaterial(arg1:string,arg2:string):Promise<models.Material>;

export function CreateProtocol(arg1:models.CreateProtocolRequest):Promise<string>;

export function GeneratePDF(arg1:string):Promise<Array<number>>;

export function GetGroupSummary(arg1:string):Promise<models.GroupSummary>;

export function GetGroups(arg1:number,arg2:number):Promise<Array<models.ExperimentGroup>>;

export function GetMaterials():Promise<Array<models.Material>>;

export function GetMethodsByStandard(arg1:string):Promise<Array<models.TestMethod>>;

export function GetProtocols(arg1:number,arg2:number):Promise<models.ProtocolListResponse>;

export function GetStandardsByMaterial(arg1:string):Promise<Array<models.Standard>>;

export function SaveProtocolPDFWithDialog(arg1:string):Promise<string>;
