// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroup(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateGroup'](arg1, arg2, arg3, arg4);
}

export function CreateMaterial(arg1, arg2) {
  return window['go']['app']['App']['CreateMaterial'](arg1, arg2);
}

export function CreateProtocol(arg1) {
  return window['go']['app']['App']['CreateProtocol'](arg1);
}

export function GeneratePDF(arg1) {
  return window['go']['app']['App']['GeneratePDF'](arg1);
}

export function GetGroupSummary(arg1) {
  return window['go']['app']['App']['GetGroupSummary'](arg1);
}

export function GetGroups(arg1, arg2) {
  return window['go']['app']['App']['GetGroups'](arg1, arg2);
}

export function GetMaterials() {
  return window['go']['app']['App']['GetMaterials']();
}

export function GetMethodsByStandard(arg1) {
  return window['go']['app']['App']['GetMethodsByStandard'](arg1);
}

export function GetProtocols(arg1, arg2) {
  return window['go']['app']['App']['GetProtocols'](arg1, arg2);
}

export function GetStandardsByMaterial(arg1) {
  return window['go']['app']['App']['GetStandardsByMaterial'](arg1);
}

export function SaveProtocolPDFWithDialog(arg1) {
  return window['go']['app']['App']['SaveProtocolPDFWithDialog'](arg1);
}
